name: CI (Continuous Integration)

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
      - name: PNPM Install
        uses: ./.github/actions/pnpm-install
      - name: Branch Checks
        uses: ./.github/actions/branch-checks
      - name: Build Web App
        uses: ./.github/actions/build-web-app
